services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: spatial-twin-platform-tunnel
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - default
